Description: >
  Manages network permissions for our public subnets

Parameters:
  Datacenter:
    Description: Naming convention of the datacenter we are creating
    Type: String

Resources:
  # Creates a Network ACL
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${Datacenter}:VpcId"

  # Open all egress and ingress traffic for private subnets 
  TCPInboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAcl
      Protocol: 6
      RuleAction: Allow
      RuleNumber: 1000
      PortRange:
        From: 0
        To: 65535

  UDPInboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAcl
      Protocol: 17
      RuleAction: Allow
      RuleNumber: 2000
      PortRange:
        From: 0
        To: 65535

  ICMPInboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAcl
      Protocol: 1
      RuleAction: Allow
      RuleNumber: 3000
      Icmp:
        Code: -1
        Type: -1

  TCPOutboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      Protocol: 6
      RuleAction: Allow
      RuleNumber: 1000
      PortRange:
        From: 0
        To: 65535

  UDPOutboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      Protocol: 17
      RuleAction: Allow
      RuleNumber: 2000
      PortRange:
        From: 0
        To: 65535

  ICMPOutboundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      Protocol: 1
      RuleAction: Allow
      RuleNumber: 3000
      Icmp:
        Code: -1
        Type: -1

  SubnetAclAssociationAZ0:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PrivateSubnetAZ0"
      NetworkAclId: !Ref NetworkAcl

  SubnetAclAssociationAZ1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PrivateSubnetAZ1"
      NetworkAclId: !Ref NetworkAcl

  SubnetAclAssociationAZ2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PrivateSubnetAZ2"
      NetworkAclId: !Ref NetworkAcl
