Description: >
  Manages network routes

Parameters:
  Datacenter:
    Description: Naming convention of the datacenter we are creating
    Type: String

Resources:
  # Maps Route Table to all 3 public AZs
  RouteTableAssociationAZ0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicSubnetAZ0"
      RouteTableId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicRouteTable"

  RouteTableAssociationAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicSubnetAZ1"
      RouteTableId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicRouteTable"

  RouteTableAssociationAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicSubnetAZ2"
      RouteTableId:
        Fn::ImportValue: !Sub "${Datacenter}:PublicRouteTable"
